sudo: required
services:
  - docker

before_install:
  - docker build -t trackercanada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trackercanada/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reactor"
  env: "DockerReactor-env"
  bucket_name: "elasticbeanstalk-us-east-2-898855534064"
  bucket_path: "docker-reactor"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
